<?php
require_once('./libs/database.php');
include_once('./widgets/header.php');
include_once('./widgets/slider.php');
include_once('./widgets/feature/feature.php');
include_once('./widgets/product/category.php');
include_once('./widgets/feature/feature_1.php');
include_once('./widgets/product/list_product.php');
include_once('./widgets/feature/feature_3.php');
include_once('./widgets/footer.php');
